Completed the file transfer cycle by adding "copyFrom" command and changing "copy" into "copyTo".
algorand/sandbox pull request #55
Opened 2021-06-23 19:33 UTC by emg110

- Changed **copy** command to **copyTo**, preserving the original functionality and argument (file)

- Added **copyFrom** to complete the cycle of file exchange between algod container in sandbox and host regarding offline authorization, offline LogicSig and TEAL.

- Updated README.md to reflect new changes.

Note: This is **not a bounty PR** but a humble contribution.

Tested and OK: 
![image](https://user-images.githubusercontent.com/1900448/123157201-7a234900-d47f-11eb-9d88-2c9ba2285b32.png)

2021-06-23 19:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/sandbox?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/sandbox?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/sandbox?pullRequest=55) it.</sub>

2021-06-23 21:27 UTC, winder requested changes
Thanks, this looks good. My only request: could you fix the alignment of the arrows?

2021-06-24 04:04 UTC, emg110 commented
Thank you, sure , yes . Right away.

2021-06-24 04:37 UTC, emg110 commented
- Fixed and updated arrows alignment in help and README.md
- Updated README.md and added an example to reflect recent changes

2021-06-24 11:55 UTC, winder approved these changes

2021-06-24 11:56 UTC, merged

2021-06-24 11:56 UTC, winder commented
Thanks for your contribution!