added support for forcing images to be rebuilt when ./sandbox clean i…
algorand/sandbox pull request #56
Opened 2021-06-26 19:14 UTC by overhead525

…s called

2021-06-26 19:17 UTC, overhead525 commented
I need to also add a commit to explain this in the README.md

However, its functionality goes hand in hand with PR #50, so let's just leave this open until we've got that one merged. Then i'll squash in another commit to update the README.md file on this PR.

2021-06-28 05:19 UTC, Mine77 commented
@fabrice102  Could you please review this bounty and provide comments to our contributor? Thank you.

2021-06-28 20:05 UTC, fabrice102 commented on sandbox
> +    docker-compose build --no-cache
You should always use `dc` instead of `docker-compose` because `dc` specify the docker-compose file

2021-06-28 20:06 UTC, fabrice102 requested changes
@overhead525 Thanks for the commit, can you make it so that `* docker-compose build --no-cache` is printed on screen or in LOG before `* docker-compose up -d`.

This would mean moving a bit the logic.
Maybe have instead a function `dc_rebuild_if_needed`, that would test if rebuilding is needed like `dc_build_with_clean_check` and then print `* docker-compose build --no-cache` (with potentially the sentence `".clean file found ..."`) and run `dc build --no-cache`.

You would then call this at line 393, 396, and 402.
Line 396, you call it with `>> "$SANDBOX_LOG"`
Lines 393 and 402, you simply call it.

Check the effect of the spinner

2021-06-28 20:06 UTC, fabrice102 commented on sandbox
> +    docker-compose build --no-cache
Use `dc` instead of `docker-compose`, as `dc` specifies correctly the `docker-compose.yml` file

2021-06-28 20:06 UTC, fabrice102 commented on sandbox
> +    CLEAN_FILE=.clean
sandbox may not be run in the correct folder, the file must be

`CLEAN_FILE="$SANDBOX_DIR/.clean"`

2021-06-28 20:06 UTC, fabrice102 commented on sandbox
> +    echo 'clean function executed' > .clean;
Same issue as above.
Simplest is to create a variable `CLEAN_FILE` that is global.

2021-06-30 16:40 UTC, overhead525 commented
> @overhead525 Thanks for the commit, can you make it so that `* docker-compose build --no-cache` is printed on screen or in LOG before `* docker-compose up -d`.
> 
> This would mean moving a bit the logic.
> Maybe have instead a function `dc_rebuild_if_needed`, that would test if rebuilding is needed like `dc_build_with_clean_check` and then print `* docker-compose build --no-cache` (with potentially the sentence `".clean file found ..."`) and run `dc build --no-cache`.
> 
> You would then call this at line 393, 396, and 402.
> Line 396, you call it with `>> "$SANDBOX_LOG"`
> Lines 393 and 402, you simply call it.
> 
> Check the effect of the spinner

I see. So currently the function `dc_build_with_clean_check` handles the checking if rebuilding is necessary AND the calling of the `dc up` command. Your request requires them to be separated. Gotcha.

2021-06-30 18:32 UTC, overhead525 commented on sandbox
>          dc up
Inside of this `if` conditional, we only have `dc up`. I wasn't sure if you guys wanted to run this new logic when the user tries **interactive mode** or not.

2021-06-30 18:40 UTC, overhead525 commented
https://github.com/algorand/sandbox/blob/df654aafecaa48f1c5371094147cd4999a74c122/sandbox#L381-L382

Inside of this `if` conditional block, we only have `dc up`. I wasn't sure if we wanted to have the rebuilding images logic if the user is in **interactive mode**. It's up to you guys.

2021-07-01 21:32 UTC, fabrice102 commented
@overhead525 I've made a PR to your PR with cleaner code. Please merge in your PR.

The main point of the PR is to show you that you can create a function to avoid duplicating codes.
Duplicated code usually quickly creates issues.
In particular in your code, you had a `>> "$SANDBOX_LOG` where it should not be.

2021-07-01 21:45 UTC, overhead525 commented
> @overhead525 I've made a PR to your PR with cleaner code. Please merge in your PR.
> 
> The main point of the PR is to show you that you can create a function to avoid duplicating codes.
> Duplicated code usually quickly creates issues.
> In particular in your code, you had a `>> "$SANDBOX_LOG` where it should not be.

Just merged. Thanks for pointing that out for me. Having a `>> $SANDBOX_LOG` is indeed indicative of the issue.

2021-07-02 17:55 UTC, winder commented
I think `>> $SANDBOX_LOG` is still wrong, if you run with `-i` you wouldn't see the rebuild output.

2021-07-02 23:46 UTC, fabrice102 commented on sandbox
> +      dc build --no-cache             >> "$SANDBOX_LOG"
```suggestion
      dc build --no-cache
```

2021-07-02 23:46 UTC, fabrice102 commented
@winder indeed, it needs to be removed. Made a suggestion above.

2021-07-06 15:35 UTC, merged